### ISSUE TITLE
False positive in non-callable called (Python)

### ISSUE THREAD

**Issue by amueller** [lgtmhq/lgtm-queries#12]
https://lgtm.com/projects/g/scikit-learn/scikit-learn/snapshot/1a981e87ba6f8d66ecfd6940184836446ded3f4c/files/sklearn/decomposition/fastica_.py#V284

The code is
```python
    elif callable(fun):
        def g(x, fun_args):
            return fun(x, **fun_args)
```
so if the code is ever reached, ``fun`` is a callable...
Seems like an issue the the type inference? Though clearly if ``fun`` is a string, this will not be reached.

**Comment by markshannon** [comment]
Thanks for the report. 
Indeed, inferring values in closures can be a little tricky, but we do have a fix this in the pipeline.

**Comment by amueller** [comment]
Sweet :) is it helpful to report these?

**Comment by sjvs** [comment]
@amueller: absolutely — keep them coming!

**Comment by amueller** [comment]
I'm not sure I have time to look into all of them right now, but I will keep them coming later :)

**Comment by markshannon** [comment]
Now fixed on lgtm.com
https://lgtm.com/projects/g/scikit-learn/scikit-learn/latest/files/sklearn/decomposition/fastica_.py?sort=name&dir=ASC&mode=heatmap&excluded=false#L284
