### ISSUE TITLE
Python false positive in using is to compare to bool

### ISSUE THREAD

**Issue by jnothman** [lgtmhq/lgtm-queries#13]
For example, https://lgtm.com/projects/g/scikit-learn/scikit-learn/snapshot/53ef71303658de05e8d02988ddb53b0714083fbc/files/sklearn/datasets/svmlight_format.py#V292 uses `var is False`. This should be acceptable. If equality rather than identity were intended, `not var` would be sufficient.

It looks like the bool case *should* be handled by `invalid_to_use_is_portably` [here](https://github.com/lgtmhq/lgtm-queries/blob/e20151eb58ca9b865c69730912aa20284e156930/python/Expressions/IsComparisons.qll#L39) (not that I've thoroughly understood the code) but it doesn't appear to be working.

**Comment by markshannon** [comment]
Thanks for the report.
What is happening here is that in the comparison `zero_based is False` we infer correctly that `zero_based` could be a string and one shouldn't, in general, compare strings using `is`.
Evidently, we are failing to account for the both sides of the comparison.

**Comment by amueller** [comment]
lol I was just about to open this one.

**Comment by markshannon** [comment]
This is now fixed.
https://lgtm.com/projects/g/scikit-learn/scikit-learn/latest/files/sklearn/datasets/svmlight_format.py?sort=name&dir=ASC&mode=heatmap&excluded=false#L292
