### ISSUE TITLE
Python wish: python 2 vs 3 division differences

### ISSUE THREAD

**Issue by jnothman** [lgtmhq/lgtm-queries#16]
A lot of Python repos aim to support both Python 2 and 3. Assuming a repository supports both 2 and 3 as regards syntax, it would be worth checking that:
* where plain division (`/` or `/=`, not `//`) is used
* if the operands can both be integers
* `from __future__ import division` is effective in that module, otherwise raise an alert

**Comment by markshannon** [comment]
Thanks for the suggestion.
Trying it on sckit-learn:
https://lgtm.com/query/2042660044/project:1870011/lang:python/
Gives quite a few results. 

I'm not sure whether to allow literal values where the result is an integer, e.g. `4/2` or not. 
The numeric value is the same, but the type is not. `[1,2,3][4/2]` is an error in Python 3, but `4/2` would be fine in a numerical calculation.

**Comment by jnothman** [comment]
Where the divisor and dividend are constant, as in
https://lgtm.com/projects/g/scikit-learn/scikit-learn/snapshot/879d1c19deb7180045788f2ad54c9871b9ecd8fc/files/examples/decomposition/plot_sparse_coding.py#L58,
it's no big deal. If it's occurring in examples, that's most often what's
happening I suspect, but I'll take a look.

**Comment by jnothman** [comment]
Obviously, as you say, there are cases where it's a big deal. Testing for
floats being used as list/array/pandas-iloc indices is obviously something
you can alert for separately.

**Comment by jnothman** [comment]
Thanks for the query!

**Comment by jnothman** [comment]
Thanks. I picked up a couple of real issues there. I'd suggest modifying the query to ignore cases where the result of the division is wrapped in `int(...)` (although `int(x/y)` differs from `int(x//y)` if the result is negative and not an integrer).

**Comment by jhelie** [comment]
Hi @jnothman, I've modified @markshannon 's query so that I think it does what you suggest. It's actually an interesting example of how to use `exists` to apply filtering logic on results.
Also note that `cls.getName() = "in"` could be equivalently replaced by `theIntType()`.
https://lgtm.com/query/2054580020/project:1870011/lang:python/

**Comment by jhelie** [comment]
Hi @jnothman, was the above useful to you?

**Comment by jhelie** [comment]
awesome - we'll close this for now then. But if you need to filter out some query results again you can always refer to the above query I linked to :)

**Comment by jnothman** [comment]
thank you!
