### ISSUE TITLE
java: false positive when FileReader throws exception

### ISSUE THREAD

**Issue by jgerhards** [lgtmhq/lgtm-queries#37]
I get this alert: 
https://lgtm.com/projects/g/jgerhards/SLFA/snapshot/3e737bd4fcb977bf27c7d8e67ef5d8f71b878193/files/src/com/rsyslog/slfa/model/LogFile.java?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x6c6356b876f728a2:1

When the ```FileReader``` throws the ```FileNotFoundException```, the static analyzer thinks the FileReader has to be closed. 

IMHO this is a false positive because
1. the file does not exist and so cannot be opened at all
2. even if 1. would not apply, I do not have a object reference, as the constructor throws the exception and so ```fr``` is not set (as the throw happens before the assignment)

As a separate note, the program exits when the exception is thrown and so there rally would be no need for manual cleanup (could be argued that this still makes sense to be flagged, but seems unhelpful).

**Comment by aschackmull** [comment]
Thank you for reporting this.  The false positive is actually unrelated to the exception handling - what happens is that it fails to recognise the flow path from `fr` through `init` and the construction of the `BufferedReader` into the `fileRd` field.  I will amend the query to handle such flow.

**Comment by samlanning** [comment]
@jgerhards it looks like the linked alerts are no longer present, so it's likely we fixed this and forgot to inform you, sorry about that!
