### ISSUE TITLE
LGTM seems to report false positives when `%m$` is used in the format string

### ISSUE THREAD

**Issue by evverx** [lgtmhq/lgtm-queries#44]
I came across https://lgtm.com/projects/g/systemd/systemd/alerts/?mode=list&lang=cpp&severity=error&rule=cpp%2Fwrong-number-format-arguments where all alerts seem to be false positives. I'm not sure how exactly QL works, but I think that `getNumArgNeeded` in the snippet below can't seem to handle `%m$` in the format string:
https://github.com/lgtmhq/lgtm-queries/blob/9705b5d124f78576f509d03ae7be83564c162ea8/cpp/Likely%20Bugs/Format/WrongNumberOfFormatArguments.ql#L28-L34

According to http://man7.org/linux/man-pages/man3/printf.3.html
>    The arguments must correspond properly (after type promotion) with
       the conversion specifier.  By default, the arguments are used in the
       order given, where each '*' (see Field width and Precision below) and
       each conversion specifier asks for the next argument (and it is an
       error if insufficiently many arguments are given).  One can also
       specify explicitly which argument is taken, at each place where an
       argument is required, by writing "%m$" instead of '%' and "*m$"
       instead of '*', where the decimal integer m denotes the position in
       the argument list of the desired argument, indexed starting from 1.

**Comment by sjvs** [comment]
Thanks for the report @evverx! The team are looking into this and will update the query ASAP.

**Comment by evverx** [comment]
All the false positives this issue was about are gone. Thank you!
