### ISSUE TITLE
The "local-variable-hides-global-variable" rule could probably be relaxed for external function declarations

### ISSUE THREAD

**Issue by evverx** [lgtmhq/lgtm-queries#47]
LGTM had shown https://lgtm.com/projects/g/systemd/systemd/snapshot/7439844465c01f80a0e47cef9db10a5062da1e9e/files/src/basic/process-util.c?#V1156 until it was fixed yesterday in https://github.com/systemd/systemd/pull/9601. As far as I can tell, `__dso_handle` there didn't hide anything and any name, or no name at all, could have equally been used with no harm. It would probably be helpful if the rule skipped variables in external function declarations.

**Comment by geoffw0** [comment]
Yes, thanks for pointing this out.  The rule should only look at the name given to a parameter in a function definition, not a declaration such as this one.  A fix is ready, though I think it's just missed the next deployment so it will take a couple of weeks to reach you.

**Comment by evverx** [comment]
The rule seems to have been fixed. Thank you. I'm closing the issue.
