### ISSUE TITLE
TypeScript: false positive for Semicolon Insertion with template string

### ISSUE THREAD

**Issue by ajafff** [lgtmhq/lgtm-queries#50]
I don't see where a semicolon would be missing.

![image](https://user-images.githubusercontent.com/11968040/44917056-9f2af800-ad37-11e8-84ec-549a326cebe6.png)

**Comment by xiemaisi** [comment]
Neither do I. Would you mind raising an issue at https://github.com/Semmle/ql/issues? That's where we do our query development these days.

**Comment by xiemaisi** [comment]
Moved to https://github.com/Semmle/ql/issues/125.
