### ISSUE TITLE
TypeScript: false positive Incomplete Sanitization with escaped backslash

### ISSUE THREAD

**Issue by ajafff** [lgtmhq/lgtm-queries#51]
The backslash is actually escaped. This false positive seems to be related to the enclosing template string.

```js
`Generator ${name === undefined ? '' : `'${name.getText(this.sourceFile).replace(/'/g, "\\'")}' `}contains no 'yield'.`
````

![image](https://user-images.githubusercontent.com/11968040/44917365-7bb47d00-ad38-11e8-899f-e33444264543.png)

Also note that the error location shows `/'/g` as the offender. But there is no backslash to be escaped.

**Comment by xiemaisi** [comment]
I don't immediately see where the escaping of the backslash happens. Could you provide a link to the original alert?

**Comment by ajafff** [comment]
@xiemaisi 
https://lgtm.com/projects/g/fimbullinter/wotan/snapshot/75747a06875fb371850c3935d6910f8bbb493af4/files/packages/mimir/src/rules/generator-require-yield.ts?sort=name&dir=ASC&mode=heatmap&showExcluded=false#xe9939675304c9e47:1

And another one
https://lgtm.com/projects/g/fimbullinter/wotan/snapshot/75747a06875fb371850c3935d6910f8bbb493af4/files/packages/wotan/src/baseline.ts#xe85427393dd6117c:1

**Comment by ajafff** [comment]
I get what that query is intended to do. But this totally depends on how the resulting string will be used later. In my case this is just text. It's not parsed or processed in some way.

I don't mind if you close this issue if you think this is working as intended.

But you could also consider rephrasing the message because it was not clear to me what it actually meant.

**Comment by xiemaisi** [comment]
Right. So this alert is expected, but I agree that the query help could be improved to clarify its meaning. I'll leave the issue open until we have fixed it.

**Comment by samlanning** [comment]
Closing and replacing with https://github.com/Semmle/ql/issues/130
